//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGV
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLGVEntities : DbContext
    {
        public QLGVEntities()
            : base("name=QLGVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACADEMIC_RANK> ACADEMIC_RANK { get; set; }
        public virtual DbSet<ACCOUNT> ACCOUNTs { get; set; }
        public virtual DbSet<ADMINISTRATIVE_POST> ADMINISTRATIVE_POST { get; set; }
        public virtual DbSet<APPLIED_TECH_PRODUCT> APPLIED_TECH_PRODUCT { get; set; }
        public virtual DbSet<AWARD> AWARDs { get; set; }
        public virtual DbSet<BOOK> BOOKs { get; set; }
        public virtual DbSet<BOOK_HISTORY> BOOK_HISTORY { get; set; }
        public virtual DbSet<BOOK_TYPE> BOOK_TYPE { get; set; }
        public virtual DbSet<CLASS> CLASSes { get; set; }
        public virtual DbSet<COUNCIL> COUNCILs { get; set; }
        public virtual DbSet<COUNCIL_HISTORY> COUNCIL_HISTORY { get; set; }
        public virtual DbSet<COUNCIL_ROLE> COUNCIL_ROLE { get; set; }
        public virtual DbSet<COUNCIL_TYPE> COUNCIL_TYPE { get; set; }
        public virtual DbSet<DEGREE> DEGREEs { get; set; }
        public virtual DbSet<DEPARTMENT> DEPARTMENTs { get; set; }
        public virtual DbSet<DT_ACADEMIC_RANK> DT_ACADEMIC_RANK { get; set; }
        public virtual DbSet<DT_ADMINISTRATIVE_POST> DT_ADMINISTRATIVE_POST { get; set; }
        public virtual DbSet<DT_AWARD> DT_AWARD { get; set; }
        public virtual DbSet<DT_BOOK> DT_BOOK { get; set; }
        public virtual DbSet<DT_Council> DT_Council { get; set; }
        public virtual DbSet<DT_DEGREE> DT_DEGREE { get; set; }
        public virtual DbSet<DT_DEPARTMENT> DT_DEPARTMENT { get; set; }
        public virtual DbSet<DT_EXAMIN> DT_EXAMIN { get; set; }
        public virtual DbSet<DT_MENTORING> DT_MENTORING { get; set; }
        public virtual DbSet<DT_PARTY_POST> DT_PARTY_POST { get; set; }
        public virtual DbSet<DT_PUNISHMENT> DT_PUNISHMENT { get; set; }
        public virtual DbSet<DT_RESEARCH> DT_RESEARCH { get; set; }
        public virtual DbSet<DT_RESEARCH_TITLE> DT_RESEARCH_TITLE { get; set; }
        public virtual DbSet<DT_RIGHT> DT_RIGHT { get; set; }
        public virtual DbSet<DT_SUBJECT_CLASS> DT_SUBJECT_CLASS { get; set; }
        public virtual DbSet<DT_TEACHING> DT_TEACHING { get; set; }
        public virtual DbSet<EDU_BRANCH> EDU_BRANCH { get; set; }
        public virtual DbSet<EDUCATION_PROCESS> EDUCATION_PROCESS { get; set; }
        public virtual DbSet<EDULEVEL> EDULEVELs { get; set; }
        public virtual DbSet<EXAMIN_HISTORY_> EXAMIN_HISTORY_ { get; set; }
        public virtual DbSet<EXAMIN_TYPE> EXAMIN_TYPE { get; set; }
        public virtual DbSet<FACULTY> FACULTies { get; set; }
        public virtual DbSet<FACULTY_HISTORY> FACULTY_HISTORY { get; set; }
        public virtual DbSet<LOAD_BY_SEMESTER> LOAD_BY_SEMESTER { get; set; }
        public virtual DbSet<LOAD_STATISTIC> LOAD_STATISTIC { get; set; }
        public virtual DbSet<MENTORING_HISTORY> MENTORING_HISTORY { get; set; }
        public virtual DbSet<MENTORING_TYPE> MENTORING_TYPE { get; set; }
        public virtual DbSet<OTHER_BUSINESS> OTHER_BUSINESS { get; set; }
        public virtual DbSet<PARTY_POST> PARTY_POST { get; set; }
        public virtual DbSet<PUNISHMENT> PUNISHMENTs { get; set; }
        public virtual DbSet<REAL_COUNCIL> REAL_COUNCIL { get; set; }
        public virtual DbSet<RESEARCH> RESEARCHes { get; set; }
        public virtual DbSet<RESEARCH_HISTORY> RESEARCH_HISTORY { get; set; }
        public virtual DbSet<RESEARCH_ROLE> RESEARCH_ROLE { get; set; }
        public virtual DbSet<RESEARCH_TITLE> RESEARCH_TITLE { get; set; }
        public virtual DbSet<RESEARCH_TYPE> RESEARCH_TYPE { get; set; }
        public virtual DbSet<RIGHT> RIGHTs { get; set; }
        public virtual DbSet<RIGHT_GROUP> RIGHT_GROUP { get; set; }
        public virtual DbSet<STUDENT> STUDENTs { get; set; }
        public virtual DbSet<SUBJECT> SUBJECTs { get; set; }
        public virtual DbSet<SUBJECT_CLASS> SUBJECT_CLASS { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TEACHER> TEACHERs { get; set; }
        public virtual DbSet<TEACHER_HISTORY> TEACHER_HISTORY { get; set; }
        public virtual DbSet<TEACHING_HISTORY> TEACHING_HISTORY { get; set; }
        public virtual DbSet<TEACHING_TYPE> TEACHING_TYPE { get; set; }
        public virtual DbSet<TECH_AWARD> TECH_AWARD { get; set; }
        public virtual DbSet<THESIS> Theses { get; set; }
        public virtual DbSet<WORKLOAD_TYPE> WORKLOAD_TYPE { get; set; }
        public virtual DbSet<WRITING_ROLE> WRITING_ROLE { get; set; }
    }
}
