//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGV
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT_Council
    {
        public string code { get; set; }
        public string codeview { get; set; }
        public string name { get; set; }
        public string note { get; set; }
        public string lastedituser { get; set; }
        public Nullable<System.DateTime> lastedittime { get; set; }
        public Nullable<short> @lock { get; set; }
        public Nullable<System.DateTime> lockdate { get; set; }
        public Nullable<int> theorder { get; set; }
        public string realcouncilcode { get; set; }
        public string teachercode { get; set; }
        public string councilrolecode { get; set; }
        public Nullable<short> semester { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<int> workloadpart { get; set; }
        public Nullable<int> yearstart { get; set; }
    
        public virtual COUNCIL_ROLE COUNCIL_ROLE { get; set; }
        public virtual REAL_COUNCIL REAL_COUNCIL { get; set; }
        public virtual TEACHER TEACHER { get; set; }
    }
}
