//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGV
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT_MENTORING
    {
        public string code { get; set; }
        public string codeview { get; set; }
        public string name { get; set; }
        public string note { get; set; }
        public string lastedituser { get; set; }
        public Nullable<System.DateTime> lastedittime { get; set; }
        public Nullable<short> @lock { get; set; }
        public Nullable<System.DateTime> lockdate { get; set; }
        public Nullable<int> theorder { get; set; }
        public string teachercode { get; set; }
        public string studentcode { get; set; }
        public string thesiscode { get; set; }
        public Nullable<System.DateTime> star { get; set; }
        public Nullable<System.DateTime> end { get; set; }
        public Nullable<short> semester { get; set; }
        public Nullable<int> workloadpart { get; set; }
        public Nullable<int> yearstart { get; set; }
    
        public virtual DT_EXAMIN DT_EXAMIN { get; set; }
        public virtual STUDENT STUDENT { get; set; }
        public virtual TEACHER TEACHER { get; set; }
        public virtual THESIS THESIS { get; set; }
    }
}
