//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGV
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDUCATION_PROCESS
    {
        public string code { get; set; }
        public string codeview { get; set; }
        public string name { get; set; }
        public string note { get; set; }
        public string lastedituser { get; set; }
        public Nullable<System.DateTime> lastedittime { get; set; }
        public Nullable<short> @lock { get; set; }
        public Nullable<System.DateTime> lockdate { get; set; }
        public Nullable<int> theorder { get; set; }
        public string teachercode { get; set; }
        public string bsedubranch { get; set; }
        public string Bsplace { get; set; }
        public string Bsspecialization { get; set; }
        public string bscountry { get; set; }
        public Nullable<System.DateTime> Bsyear { get; set; }
        public string msspecialzation { get; set; }
        public Nullable<System.DateTime> yearms { get; set; }
        public string msthesisname { get; set; }
        public string phdspeciallization { get; set; }
        public Nullable<System.DateTime> yearphd { get; set; }
        public string phdthesisname { get; set; }
    
        public virtual TEACHER TEACHER { get; set; }
    }
}
