//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGV
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDULEVEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EDULEVEL()
        {
            this.EDU_BRANCH = new HashSet<EDU_BRANCH>();
            this.MENTORING_TYPE = new HashSet<MENTORING_TYPE>();
        }
    
        public string code { get; set; }
        public string codeview { get; set; }
        public string name { get; set; }
        public string note { get; set; }
        public string lastedituser { get; set; }
        public Nullable<System.DateTime> lastedittime { get; set; }
        public Nullable<short> @lock { get; set; }
        public Nullable<System.DateTime> lockdate { get; set; }
        public Nullable<int> theorder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EDU_BRANCH> EDU_BRANCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENTORING_TYPE> MENTORING_TYPE { get; set; }
    }
}
