//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGV
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACULTY_HISTORY
    {
        public string code { get; set; }
        public string codeview { get; set; }
        public string name { get; set; }
        public string note { get; set; }
        public string lastedituser { get; set; }
        public Nullable<System.DateTime> lastedittime { get; set; }
        public Nullable<short> @lock { get; set; }
        public Nullable<System.DateTime> lockdate { get; set; }
        public Nullable<int> theorder { get; set; }
        public string facultycode { get; set; }
        public string facultyname { get; set; }
        public Nullable<int> totalnumber { get; set; }
        public Nullable<int> profnumber { get; set; }
        public Nullable<int> asprofnumber { get; set; }
        public Nullable<int> doctorscinumber { get; set; }
        public Nullable<int> doctornumber { get; set; }
        public Nullable<int> masternumber { get; set; }
        public Nullable<int> bachelornumber { get; set; }
        public Nullable<int> otherpeoplenumber { get; set; }
        public Nullable<int> totaltitle { get; set; }
        public Nullable<int> seniorlecturenumber { get; set; }
        public Nullable<int> lecturenumber { get; set; }
        public Nullable<int> atstartnumber { get; set; }
        public string dtcode { get; set; }
    
        public virtual FACULTY FACULTY { get; set; }
    }
}
