//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGV
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAD_STATISTIC
    {
        public string code { get; set; }
        public string codeview { get; set; }
        public string name { get; set; }
        public string note { get; set; }
        public string lastedituser { get; set; }
        public Nullable<System.DateTime> lastedittime { get; set; }
        public Nullable<short> @lock { get; set; }
        public Nullable<System.DateTime> lockdate { get; set; }
        public Nullable<int> theorder { get; set; }
        public string teachercode { get; set; }
        public string teachername { get; set; }
        public string departmentname { get; set; }
        public string facultyname { get; set; }
        public Nullable<System.DateTime> start { get; set; }
        public Nullable<System.DateTime> end { get; set; }
        public Nullable<int> realteachingload { get; set; }
        public Nullable<int> requiredteachingload { get; set; }
        public Nullable<int> teachingratio { get; set; }
        public Nullable<int> realresearchload { get; set; }
        public Nullable<int> requiredresearchload { get; set; }
        public Nullable<int> researchratio { get; set; }
        public Nullable<int> totalrealload { get; set; }
        public Nullable<int> totalrequiredload { get; set; }
    
        public virtual TEACHER TEACHER { get; set; }
    }
}
